version: "3.9"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile-PostgreSQL
    image: postgresql
    env_file:
      - ./env/development.env
    expose:
      - "5432"
    volumes:
      - ./:/app

  web:
    image: node:14-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - ./env/development.env
    command: "npm start"
    depends_on:
      - database
