FROM ubuntu:groovy
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Toronto
RUN apt-get update
RUN apt-get --assume-yes install postgresql
RUN apt-get --assume-yes install pgtap

WORKDIR /app
COPY . .

USER postgres
RUN /etc/init.d/postgresql start &&\
    psql --command "CREATE USER microlearner WITH SUPERUSER;" &&\
    createdb -O microlearner microlearner
RUN echo "host all  all    0.0.0.0/0  trust\nlocal all all trust" > /etc/postgresql/12/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/12/main/postgresql.conf

CMD ["/usr/lib/postgresql/12/bin/postgres", "-D", "/var/lib/postgresql/12/main", "-c", "config_file=/etc/postgresql/12/main/postgresql.conf"]
